import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Facial Recognition",
  description: "Generated by Facial Recognition",
     icons: {
    icon: "/favicon01.png",
  },

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        {children}</body>
    </html>
  );
}
